### ISSUE TITLE
关于4K内屏黑屏的问题，请指教

### ISSUE THREAD

**Issue by RockJesus** [crackself/Dell-7559-Hackintosh#1]
你好，
我的本子是 DELL 15 7559 I7 6700HQ 4K触摸屏 UEFI 引导10.12.4 连接了一台HDMI显示器
A:clover 设置injectintel=no fakeid=无 ig=无 开机HDMI显示器驱动正常有透明，内屏黑屏但是有光，显卡驱动显示intel skl 1500M
B::clover 设置injectintel=YES fakeid=0x12345678 ig=0x191b0000 开机HDMI显示器和内屏都亮但是都没有驱动无透明，显卡驱动显示intel hd530 31M
4k补丁也打过无效果
请问有什么办法吗，谢谢啦~~~

**Comment by crackself** [comment]
我没4K屏幕，不太了解。建议你参考这两个教程：
https://www.tonymacx86.com/threads/guide-dell-inspiron-15-7559-sierra-install-10-12-5.201576/
https://www.tonymacx86.com/threads/guide-dell-inspiron-15-7559-el-capitan-hackintosh-dual-boot-with-windows.196138/
