### ISSUE TITLE
黑苹果

### ISSUE THREAD

**Issue by qiezihwy** [crackself/Dell-7559-Hackintosh#3]
你好，请问你的dell-7559-hackintosh /hotpatch/installer/clover是dell7559可以用这个的efi吗，另外那个DSDT+SSDT_Hotpatch文件夹里的东西是不是已经放到了dell-7559-hackintosh /hotpatch/installer/clover文件夹啊。

**Comment by crackself** [comment]
7559k可以用。
DSDT+SSDT_Hotpatch与纯hotpatch不一样，看详细文件说明，不要混用

**Comment by qiezihwy** [comment]
>7559k可以用。 ...

@crackself嗯嗯。我今天直接用了dell-7559-hackintosh/hotpatch/post install/clover装了，成功进入系统，显卡也成功驱动了，但是亮度不能用快捷键调节，而且去设置里面点击亮度条调节直接就黑屏了。请问，我是要用DSDT+SSDT_hotpatch里面的那个调节亮度的插件放进去吗


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by qiezihwy** [comment]
>>7559k可以用。 ... ...

@qiezihwy不对，是整个patched文件夹都要换掉还有config文件也得换是吧

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by crackself** [comment]
SSDt-pnlf要自己定制，不同机型不一样代码，你看我提供的链接，里面有原版教程

**Comment by qiezihwy** [comment]
>SSDt-pnlf要自己定制，不同机型不一样代码，你看我提供的链接，里面有原版教程

@crackself那里面的三个是只有pnlf是需要自己定制的吗


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by qiezihwy** [comment]
>和亮度调节有关的包括电池补丁，所以，理论上都要按本机情况定制

@crackself嗯嗯，我过几天再试试，这几个星期考试就先不弄了😂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by luzibuye** [comment]
请问10.13.5用的还是1.0.1版本的bios吗？另外这个efi也支持10.13.5吗？

**Comment by shijiav** [comment]
这还是两年前那个拔电启动的版本吗

**Comment by crackself** [comment]
@luzibuye @shijiav https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md
